const config = {
  AWS_REGION: 'YOUR_AWS_REGION',
  AWS_COGNITO_IDENTITY_POOL_ID: 'YOUR_ID_POOL',
  AWS_COGNITO_USER_POOL_ID: 'YOUR_USER_POOL_ID',
  AWS_COGNITO_CLIENT_ID: 'YOUR_CLIENT_ID',
  AWS_COGNITO_CLIENT_DOMAIN_NAME: 'YOUR_COGNITO_DOMAIN_NAME',
  AWS_COGNITO_IDP_NAME: 'YOUR_IDP_NAME',
  AWS_COGNITO_IDP_SIGNIN_URL: 'OAUTH_SIGNIN_URL',
  AWS_COGNITO_IDP_SIGNOUT_URL: 'OAUTH_SIGNOUT_URL',
  AWS_COGNITO_IDP_OAUTH_CLAIMS: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
  AWS_COGNITO_IDP_GRANT_FLOW: 'code' // 'code' or 'token'
};

export default config;
